// Generated by ChatGPT
// 大半はChatGPTの生成

#[cfg(test)]
mod tests {
    use crate::{PackratAndPrattParser, common::tests::tests::*};
    use musubu_ast::*;
    use musubu_primitive::*;
    use musubu_span::*;

    const DUMMY_SPAN: Span = Span {
        file_id: 0,
        start: 0,
        end: 0,
    };

    trait SpannedTestUtility<T> {
        fn unwrap_node(self) -> T;
    }

    impl<T> SpannedTestUtility<T> for Spanned<T> {
        fn unwrap_node(self) -> T {
            self.node
        }
    }

    fn sp<T>(node: T) -> Spanned<T> {
        Spanned {
            node,
            span: DUMMY_SPAN,
        }
    }

    fn sp_box<T>(node: T) -> SpannedBox<T> {
        Spanned {
            node: Box::new(node),
            span: DUMMY_SPAN,
        }
    }

    fn eq_expr(a: &Expression, b: &Expression) -> bool {
        use Expression::*;

        match (a, b) {
            (Literal(a), Literal(b)) => a.node == b.node,

            (Path(a), Path(b)) => eq_path(&a.node, &b.node),

            (
                Binary {
                    operator: op1,
                    left: l1,
                    right: r1,
                },
                Binary {
                    operator: op2,
                    left: l2,
                    right: r2,
                },
            ) => op1 == op2 && eq_expr(&l1.node, &l2.node) && eq_expr(&r1.node, &r2.node),

            (
                Assign {
                    operator: op1,
                    left: l1,
                    right: r1,
                },
                Assign {
                    operator: op2,
                    left: l2,
                    right: r2,
                },
            ) => op1 == op2 && eq_expr(&l1.node, &l2.node) && eq_expr(&r1.node, &r2.node),

            (
                Comparison {
                    operator: op1,
                    left: l1,
                    right: r1,
                },
                Comparison {
                    operator: op2,
                    left: l2,
                    right: r2,
                },
            ) => op1 == op2 && eq_expr(&l1.node, &l2.node) && eq_expr(&r1.node, &r2.node),

            (
                Logical {
                    operator: op1,
                    left: l1,
                    right: r1,
                },
                Logical {
                    operator: op2,
                    left: l2,
                    right: r2,
                },
            ) => op1 == op2 && eq_expr(&l1.node, &l2.node) && eq_expr(&r1.node, &r2.node),

            (Array { elements: e1 }, Array { elements: e2 }) => eq_array(e1, e2),

            (
                Call {
                    function: f1,
                    arguments: a1,
                },
                Call {
                    function: f2,
                    arguments: a2,
                },
            ) => {
                eq_expr(&f1.node, &f2.node)
                    && a1.len() == a2.len()
                    && a1.iter().zip(a2).all(|(x, y)| eq_expr(&x.node, &y.node))
            }

            (
                FieldAccess {
                    parent: p1,
                    field_name: f1,
                },
                FieldAccess {
                    parent: p2,
                    field_name: f2,
                },
            ) => f1 == f2 && eq_expr(&p1.node, &p2.node),

            (MethodCall(m1), MethodCall(m2)) => {
                m1.name == m2.name
                    && m1.params.len() == m2.params.len()
                    && m1
                        .params
                        .iter()
                        .zip(&m2.params)
                        .all(|(a, b)| eq_expr(&a.node, &b.node))
            }

            (
                Index {
                    parent: p1,
                    index: i1,
                },
                Index {
                    parent: p2,
                    index: i2,
                },
            ) => eq_expr(&p1.node, &p2.node) && eq_expr(&i1.node, &i2.node),

            (Block(s1), Block(s2)) => {
                s1.len() == s2.len() && s1.iter().zip(s2).all(|(a, b)| eq_stmt(&a.node, &b.node))
            }

            (Loop(l1), Loop(l2)) => eq_loop(&l1.node, &l2.node),

            (
                If {
                    condition: c1,
                    then_body: t1,
                    else_body: e1,
                },
                If {
                    condition: c2,
                    then_body: t2,
                    else_body: e2,
                },
            ) => {
                eq_expr(&c1.node, &c2.node)
                    && eq_expr(&t1.node, &t2.node)
                    && match (e1, e2) {
                        (Some(a), Some(b)) => eq_expr(&a.node, &b.node),
                        (None, None) => true,
                        _ => false,
                    }
            }

            (Continue { label: l1 }, Continue { label: l2 }) => l1 == l2,

            (
                Break {
                    label: l1,
                    expression: e1,
                },
                Break {
                    label: l2,
                    expression: e2,
                },
            ) => {
                l1 == l2
                    && match (e1, e2) {
                        (Some(a), Some(b)) => eq_expr(&a.node, &b.node),
                        (None, None) => true,
                        _ => false,
                    }
            }

            (Return(a), Return(b)) => match (a, b) {
                (Some(a), Some(b)) => eq_expr(&a.node, &b.node),
                (None, None) => true,
                _ => false,
            },

            _ => false,
        }
    }

    fn eq_path(a: &Path, b: &Path) -> bool {
        a.segments.len() == b.segments.len()
            && a.segments.iter().zip(&b.segments).all(|(x, y)| {
                x.node.ident == y.node.ident && x.node.arguments.len() == y.node.arguments.len()
            })
    }

    fn eq_stmt(a: &Statement, b: &Statement) -> bool {
        match (a, b) {
            (Statement::Semicolon, Statement::Semicolon) => true,

            (Statement::Expression(a), Statement::Expression(b)) => eq_expr(&a.node, &b.node),

            (
                Statement::Let {
                    name: n1,
                    initializer: i1,
                    ..
                },
                Statement::Let {
                    name: n2,
                    initializer: i2,
                    ..
                },
            ) => {
                n1.node == n2.node
                    && match (i1, i2) {
                        (Some(a), Some(b)) => eq_expr(&a.node, &b.node),
                        (None, None) => true,
                        _ => false,
                    }
            }

            (Statement::Item(a), Statement::Item(b)) => a.node == b.node,

            _ => false,
        }
    }

    fn eq_loop(a: &LoopExpr, b: &LoopExpr) -> bool {
        match (a, b) {
            (
                LoopExpr::While {
                    condition: c1,
                    body: b1,
                },
                LoopExpr::While {
                    condition: c2,
                    body: b2,
                },
            ) => eq_expr(&c1.node, &c2.node) && eq_expr(&b1.node, &b2.node),

            (
                LoopExpr::For {
                    pattern: p1,
                    iterator: i1,
                    body: b1,
                },
                LoopExpr::For {
                    pattern: p2,
                    iterator: i2,
                    body: b2,
                },
            ) => p1.node == p2.node && eq_expr(&i1.node, &i2.node) && eq_expr(&b1.node, &b2.node),

            (LoopExpr::Loop { body: b1 }, LoopExpr::Loop { body: b2 }) => {
                eq_expr(&b1.node, &b2.node)
            }

            _ => false,
        }
    }

    fn eq_array(a: &ArrayElements, b: &ArrayElements) -> bool {
        match (a, b) {
            (ArrayElements::List(a), ArrayElements::List(b)) => {
                a.len() == b.len() && a.iter().zip(b).all(|(x, y)| eq_expr(&x.node, &y.node))
            }

            (
                ArrayElements::Repeat {
                    value: v1,
                    count: c1,
                },
                ArrayElements::Repeat {
                    value: v2,
                    count: c2,
                },
            ) => eq_expr(&v1.node, &v2.node) && eq_expr(&c1.node, &c2.node),

            _ => false,
        }
    }

    fn int_lit(v: &str) -> Expression {
        Expression::Literal(sp(Literal::Integer {
            value: v.to_string(),
            value_type: TypeKind::Primitive(PrimitiveType::default_integer()),
        }))
    }

    fn ident_expr(name: &str) -> Expression {
        Expression::Path(sp(Path {
            segments: vec![sp(PathSegment {
                ident: name.to_string(),
                arguments: vec![],
            })],
        }))
    }

    fn wrap_fn(src: &str) -> String {
        format!("fn main() {{ {} }}", src)
    }

    fn parse_fn_err(src: &str) {
        parse_err(&wrap_fn(src));
    }

    fn parse_err(src: &str) {
        let result = PackratAndPrattParser::new(tokenize_from_str(src)).parse();
        assert!(
            result.is_err(),
            "expected error but parsed successfully: {}\n{:#?}",
            src,
            result.unwrap()
        );
    }

    // 必ずItemを含む必要がある
    fn parsed_fn(body: &str) -> ASTNode {
        let wrapped_body = wrap_fn(body);
        parsed(&wrapped_body)
    }

    fn extract(node: ASTNode) -> Vec<Statement> {
        let ASTNode::Item { item, .. } = node else {
            panic!();
        };

        let Item::Function { body, .. } = item.node else {
            panic!();
        };

        let body = body.unwrap();

        let Expression::Block(statements) = *body.node else {
            panic!();
        };

        statements.into_iter().map(|s| s.node).collect()
    }

    fn extract_first(node: ASTNode) -> Statement {
        extract(node)[0].clone()
    }

    //
    fn extract_first_expr(node: ASTNode) -> Expression {
        let statement = extract_first(node);
        let Statement::Expression(expr) = statement else {
            panic!("{statement:#?}");
        };

        *expr.node
    }

    // =========================
    // Expression
    // =========================

    #[test]
    fn test_binary_expression() {
        let node = extract_first_expr(parsed_fn("1 + 2;"));

        let expected = Expression::Binary {
            operator: BinaryOperator::Addition,
            left: sp_box(int_lit("1")),
            right: sp_box(int_lit("2")),
        };

        assert!(eq_expr(&node, &expected));
    }

    #[test]
    fn test_operator_precedence() {
        let node = extract_first_expr(parsed_fn("1 + 2 * 3;"));
        let expected = Expression::Binary {
            operator: BinaryOperator::Addition,
            left: sp_box(int_lit("1")),
            right: sp_box(Expression::Binary {
                operator: BinaryOperator::Multiply,
                left: sp_box(int_lit("2")),
                right: sp_box(int_lit("3")),
            }),
        };

        assert!(eq_expr(&node, &expected));
    }

    #[test]
    fn test_assign_expression() {
        let node = extract_first_expr(parsed_fn("a = 10;"));
        let expected = Expression::Assign {
            operator: AssignOperator::Assign,
            left: sp_box(ident_expr("a")),
            right: sp_box(int_lit("10")),
        };

        assert!(eq_expr(&node, &expected));
    }

    #[test]
    fn test_comparison_expression() {
        let node = extract_first_expr(parsed_fn("a == b;"));
        let expected = Expression::Comparison {
            operator: ComparisonOperator::Equal,
            left: sp_box(ident_expr("a")),
            right: sp_box(ident_expr("b")),
        };

        assert!(eq_expr(&node, &expected));
    }

    // =========================
    // If variations
    // =========================

    #[test]
    fn test_if_expression() {
        let node = extract_first_expr(parsed_fn("if a { b; }"));
        let Expression::If { condition, .. } = node else {
            panic!();
        };

        assert!(eq_expr(&condition.node, &ident_expr("a")));
    }

    #[test]
    fn test_if_else_basic() {
        let node = extract_first_expr(parsed_fn("if a { b; } else { c; }"));

        let Expression::If {
            condition,
            then_body,
            else_body,
        } = node
        else {
            panic!();
        };

        assert!(eq_expr(&condition.node, &ident_expr("a")));

        let Expression::Block(then_stmts) = &*then_body.node else {
            panic!();
        };
        let Statement::Expression(expr) = &then_stmts[0].node else {
            panic!();
        };
        assert!(eq_expr(&expr.node, &ident_expr("b")));

        let else_body = else_body.unwrap();
        let Expression::Block(else_stmts) = &*else_body.node else {
            panic!();
        };
        let Statement::Expression(expr) = &else_stmts[0].node else {
            panic!();
        };
        assert!(eq_expr(&expr.node, &ident_expr("c")));
    }

    #[test]
    fn test_if_nested() {
        let node = extract_first_expr(parsed_fn("if a { if b { c; } }"));

        let Expression::If { then_body, .. } = node else {
            panic!();
        };

        let Expression::Block(stmts) = &*then_body.node else {
            panic!();
        };

        let Statement::Expression(inner) = &stmts[0].node else {
            panic!();
        };

        let Expression::If { condition, .. } = &*inner.node else {
            panic!();
        };

        assert!(eq_expr(&condition.node, &ident_expr("b")));
    }

    #[test]
    fn test_if_multi() {
        let statements = extract(parsed_fn(
            "if a == b { let a = 1; } if c != d { let b = 2; } ",
        ));

        for statement in statements {
            let Statement::Expression(expr) = statement else {
                panic!("{statement:#?}");
            };
            let Expression::If { then_body, .. } = &*expr.node else {
                panic!("{expr:#?}");
            };
            let Expression::Block(stmts) = &*then_body.node else {
                panic!("{then_body:#?}");
            };
            let Statement::Let { .. } = &stmts[0].node else {
                panic!("{stmts:#?}");
            };
        }
    }

    #[test]
    fn test_if_else_if_chain() {
        let node = extract_first_expr(parsed_fn("if a { b; } else if c { d; } else { e; }"));

        let Expression::If {
            condition,
            else_body,
            ..
        } = node
        else {
            panic!();
        };

        assert!(eq_expr(&condition.node, &ident_expr("a")));

        // else if
        let else_body = else_body.unwrap();
        let Expression::If {
            condition: cond2,
            else_body: else2,
            ..
        } = &*else_body.node
        else {
            panic!();
        };

        assert!(eq_expr(&cond2.node, &ident_expr("c")));

        // final else
        let else2 = else2.as_ref().unwrap();
        let Expression::Block(stmts) = &*else2.node else {
            panic!();
        };

        let Statement::Expression(expr) = &stmts[0].node else {
            panic!();
        };

        assert!(eq_expr(&expr.node, &ident_expr("e")));
    }

    #[test]
    fn test_if_complex_condition() {
        let node = extract_first_expr(parsed_fn("if a + b * c == d { e; }"));

        let Expression::If { condition, .. } = node else {
            panic!();
        };
        let Expression::Comparison { operator, .. } = *condition.node else {
            panic!("{condition:#?}");
        };

        assert_eq!(operator, ComparisonOperator::Equal);
    }

    #[test]
    fn test_if_with_logical_condition() {
        let node = extract_first_expr(parsed_fn("if a && b || c { d; }"));

        let Expression::If { condition, .. } = node else {
            panic!();
        };
        let Expression::Logical { operator, .. } = *condition.node else {
            panic!();
        };

        assert_eq!(operator, LogicalOperator::Or);
    }

    #[test]
    fn test_if_deep_nested_else_if() {
        let node = extract_first_expr(parsed_fn(
            "if a { b; } else if c { d; } else if e { f; } else { g; }",
        ));

        let Expression::If { else_body, .. } = node else {
            panic!();
        };

        // 1段目 else-if
        let Expression::If { else_body, .. } = *else_body.unwrap().node else {
            panic!();
        };

        // 2段目 else-if
        let Expression::If { else_body, .. } = *else_body.unwrap().node else {
            panic!();
        };

        // 最終 else
        let Expression::Block(stmts) = *else_body.unwrap().node else {
            panic!();
        };

        let Statement::Expression(expr) = &stmts[0].node else {
            panic!();
        };

        assert!(eq_expr(&expr.node, &ident_expr("g")));
    }

    #[test]
    fn test_loop_while() {
        let node = extract_first_expr(parsed_fn("while a { b; }"));
        let Expression::Loop(loop_expr) = node else {
            panic!();
        };

        let LoopExpr::While { condition, .. } = loop_expr.node else {
            panic!();
        };

        assert!(eq_expr(&condition.node, &ident_expr("a")));
    }

    #[test]
    fn test_loop_for() {
        let node = extract_first_expr(parsed_fn("for a in b { c; }"));

        let Expression::Loop(loop_expr) = node else {
            panic!();
        };

        let LoopExpr::For { pattern, .. } = loop_expr.node else {
            panic!();
        };

        let Pattern::Identifier { ident, .. } = pattern.node else {
            panic!();
        };

        assert_eq!(ident, "a");
    }

    #[test]
    fn test_return_expression() {
        let node = extract_first_expr(parsed_fn("return 10;"));
        let Expression::Return(expr) = node else {
            panic!();
        };

        let expr = expr.unwrap();
        assert!(eq_expr(&expr.node, &int_lit("10")));
    }

    // =========================
    // Statement
    // =========================

    #[test]
    fn test_let_statement() {
        let node = extract_first(parsed_fn("let a = 10;"));
        let Statement::Let {
            name, initializer, ..
        } = node
        else {
            panic!();
        };

        let Pattern::Identifier { ident, .. } = name.node else {
            panic!();
        };

        assert_eq!(ident, "a");

        let initializer = initializer.unwrap();
        assert!(eq_expr(&initializer.node, &int_lit("10")));
    }

    #[test]
    fn test_nested_blocks() {
        let statements = extract(parsed_fn("{{{{{{{{{{{{{{{{}}}}}}}}}}}}}}}}"));
        let mut stack: Vec<&Statement> = statements.iter().collect();

        while let Some(statement) = stack.pop() {
            let Statement::Expression(expr) = statement else {
                panic!("{statement:#?}");
            };
            let Expression::Block(inner_statements) = expr.get_node() else {
                panic!("{statement:#?}");
            };
            stack.extend(inner_statements.iter().map(|s| &s.node));
        }
    }

    #[test]
    fn test_multi_blocks() {
        let statements = extract(parsed_fn("{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}"));

        for statement in statements {
            let Statement::Expression(expr) = statement else {
                panic!("{statement:#?}");
            };
            let Expression::Block(innser) = expr.get_node() else {
                panic!("{expr:#?}");
            };
            assert!(innser.is_empty());
        }
    }

    // =========================
    // Item
    // =========================

    #[test]
    fn test_function_item() {
        let node = parsed("fn main() {}");
        let ASTNode::Item { item, .. } = node else {
            panic!();
        };

        let Item::Function { name, params, .. } = item.node else {
            panic!();
        };

        assert_eq!(name, "main");
        assert!(params.is_empty());
    }

    #[test]
    fn test_function_single_param_with_return_type() {
        let node = parsed("fn add(a: i32) -> i32 { return a; }");

        let ASTNode::Item { item, .. } = node else {
            panic!()
        };

        let Item::Function {
            name,
            params,
            return_type,
            body,
        } = item.node
        else {
            panic!()
        };

        assert_eq!(name, "add");
        assert_eq!(params.len(), 1);

        let Pattern::Identifier { ident, .. } =
            params[0].node.pattern.as_ref().cloned().unwrap().node
        else {
            panic!()
        };

        assert_eq!(ident, "a");
        assert!(return_type.is_some());

        let body = body.unwrap();

        let Expression::Block(stmts) = *body.node else {
            panic!()
        };

        let Statement::Expression(expr) = &stmts[0].node else {
            panic!()
        };

        let Expression::Return(Some(inner)) = &*expr.node else {
            panic!()
        };

        assert!(eq_expr(&inner.node, &ident_expr("a")));
    }

    #[test]
    fn test_function_multiple_params() {
        let node = parsed("fn add(a: i32, b: i32) { a + b; }");

        let ASTNode::Item { item, .. } = node else {
            panic!()
        };
        let Item::Function { params, body, .. } = item.node else {
            panic!()
        };

        assert_eq!(params.len(), 2);

        let body = body.unwrap();

        let Expression::Block(stmts) = *body.node else {
            panic!()
        };

        let Statement::Expression(expr) = &stmts[0].node else {
            panic!()
        };

        let Expression::Binary { operator, .. } = &*expr.node else {
            panic!()
        };

        assert_eq!(*operator, BinaryOperator::Addition);
    }

    #[test]
    fn test_function_with_let_and_return() {
        let node = parsed("fn f(a: i32) -> i32 { let x = a * 2; return x; }");

        let ASTNode::Item { item, .. } = node else {
            panic!()
        };
        let Item::Function { body, .. } = item.node else {
            panic!()
        };

        let body = body.unwrap();

        let Expression::Block(stmts) = *body.node else {
            panic!()
        };

        assert_eq!(stmts.len(), 2);

        // let
        let Statement::Let {
            name, initializer, ..
        } = &stmts[0].node
        else {
            panic!()
        };

        let Pattern::Identifier { ident, .. } = &name.node else {
            panic!()
        };
        assert_eq!(ident, "x");

        let initializer = initializer.as_ref().unwrap();
        let Expression::Binary { operator, .. } = &*initializer.node else {
            panic!()
        };
        assert_eq!(*operator, BinaryOperator::Multiply);

        // return
        let Statement::Expression(expr) = &stmts[1].node else {
            panic!()
        };

        let Expression::Return(Some(inner)) = &*expr.node else {
            panic!()
        };

        assert!(eq_expr(&inner.node, &ident_expr("x")));
    }

    #[test]
    fn test_function_with_if() {
        let node = parsed("fn f(a: i32) -> i32 { if a { return 1; } else { return 2; } }");

        let ASTNode::Item { item, .. } = node else {
            panic!()
        };
        let Item::Function { body, .. } = item.node else {
            panic!()
        };

        let body = body.unwrap();

        let Expression::Block(stmts) = *body.node else {
            panic!()
        };
        let Statement::Expression(expr) = &stmts[0].node else {
            panic!()
        };
        let Expression::If { condition, .. } = &*expr.node else {
            panic!()
        };

        assert!(eq_expr(&condition.node, &ident_expr("a")));
    }

    #[test]
    fn test_function_with_loop() {
        let node = parsed("fn f() { loop { break; } }");

        let ASTNode::Item { item, .. } = node else {
            panic!()
        };
        let Item::Function { body, .. } = item.node else {
            panic!()
        };

        let body = body.unwrap();

        let Expression::Block(stmts) = *body.node else {
            panic!()
        };
        let Statement::Expression(expr) = &stmts[0].node else {
            panic!()
        };
        let Expression::Loop(loop_expr) = &*expr.node else {
            panic!()
        };
        let LoopExpr::Loop { body } = &loop_expr.node else {
            panic!()
        };
        let Expression::Block(inner) = &*body.node else {
            panic!()
        };
        let Statement::Expression(expr) = &inner[0].node else {
            panic!()
        };
        let Expression::Break { .. } = &*expr.node else {
            panic!()
        };
    }

    #[test]
    fn test_function_with_call() {
        let node = parsed("fn f() { foo(1, 2); }");

        let ASTNode::Item { item, .. } = node else {
            panic!()
        };
        let Item::Function { body, .. } = item.node else {
            panic!()
        };

        let body = body.unwrap();

        let Expression::Block(stmts) = *body.node else {
            panic!()
        };

        let Statement::Expression(expr) = &stmts[0].node else {
            panic!()
        };

        let Expression::Call {
            function,
            arguments,
        } = &*expr.node
        else {
            panic!()
        };

        assert!(eq_expr(&function.node, &ident_expr("foo")));
        assert_eq!(arguments.len(), 2);
    }

    #[test]
    fn test_struct_item() {
        let node = parsed("struct A { x: i32 }");

        let ASTNode::Item { item, .. } = node else {
            panic!()
        };

        let Item::Struct { name, fields } = item.node else {
            panic!()
        };

        assert_eq!(name, "A");
        assert_eq!(fields.len(), 1);
    }

    #[test]
    fn test_enum_item() {
        let node = parsed("enum A { B }");

        let ASTNode::Item { item, .. } = node else {
            panic!()
        };

        let Item::Enumeration { name, items } = item.node else {
            panic!()
        };

        assert_eq!(name, "A");
        assert_eq!(items.len(), 1);
    }

    #[test]
    fn test_enum_items() {
        let node = parsed("enum A { B, C, D, E }");

        let ASTNode::Item { item, .. } = node else {
            panic!()
        };

        let Item::Enumeration { name, items } = item.node else {
            panic!()
        };

        assert_eq!(name, "A");
        assert_eq!(items.len(), 4);
    }

    // =========================
    // Type
    // =========================

    #[test]
    fn test_type_path() {
        let ty = TypeKind::make_single_type("i32".to_string(), DUMMY_SPAN);
        let TypeKind::PathType(path) = ty else {
            panic!();
        };

        assert_eq!(path.node.segments[0].node.ident, "i32");
    }

    #[test]
    fn test_function_type() {
        let ty = TypeKind::Function {
            params: vec![sp(TypeKind::Primitive(PrimitiveType::Unit))],
            return_type: sp_box(TypeKind::Primitive(PrimitiveType::Unit)),
        };

        match ty {
            TypeKind::Function { params, .. } => {
                assert_eq!(params.len(), 1);
            }
            _ => panic!(),
        }
    }

    // =========================
    // Pattern
    // =========================

    #[test]
    fn test_pattern_identifier() {
        let pattern = Pattern::Identifier {
            ident: "a".to_string(),
            mutable: false,
            reference: false,
        };
        let Pattern::Identifier { ident, .. } = pattern else {
            panic!();
        };

        assert_eq!(ident, "a");
    }

    #[test]
    fn test_pattern_tuple_like() {
        let pattern = Pattern::Multiply(vec![
            sp(Pattern::Identifier {
                ident: "a".to_string(),
                mutable: false,
                reference: false,
            }),
            sp(Pattern::Identifier {
                ident: "b".to_string(),
                mutable: false,
                reference: false,
            }),
        ]);

        match pattern {
            Pattern::Multiply(v) => assert_eq!(v.len(), 2),
            _ => panic!(),
        }
    }

    //

    // 基本構文エラー

    #[test]
    fn test_error_empty_expression() {
        parse_err(";");
    }

    #[test]
    fn test_error_incomplete_binary() {
        parse_err("1 + ;");
    }

    #[test]
    fn test_error_missing_rhs() {
        parse_err("a = ;");
    }

    #[test]
    fn test_error_missing_lhs() {
        parse_err("= 10;");
    }

    #[test]
    fn test_error_unclosed_paren() {
        parse_err("(1 + 2;");
    }

    #[test]
    fn test_error_unclosed_block() {
        parse_err("{ let a = 10;");
    }

    #[test]
    fn test_error_extra_closing() {
        parse_err("1 + 2);");
    }

    // if

    #[test]
    fn test_error_if_no_condition() {
        parse_err("if { 1; }");
    }

    #[test]
    fn test_error_if_no_block() {
        parse_err("if a;");
    }

    #[test]
    fn test_error_else_without_if() {
        parse_err("else { 1; }");
    }

    #[test]
    fn test_error_while_no_condition() {
        parse_err("while { 1; }");
    }

    #[test]
    fn test_error_for_invalid_syntax() {
        parse_err("for in a { }");
    }

    #[test]
    fn test_error_let_no_name() {
        parse_err("let = 10;");
    }

    // let

    #[test]
    fn test_error_let_no_initializer() {
        parse_err("let a = ;");
    }

    #[test]
    fn test_error_let_invalid_pattern() {
        parse_err("let 123 = 10;");
    }

    // 関数

    #[test]
    fn test_error_fn_no_name() {
        parse_err("fn () {}");
    }

    #[test]
    fn test_error_fn_unclosed_params() {
        parse_err("fn main( {}");
    }

    #[test]
    fn test_error_fn_invalid_param() {
        parse_err("fn main(a i32) {}");
    }

    #[test]
    fn test_error_struct_invalid_field() {
        parse_err("struct A { x i32 }");
    }

    #[test]
    fn test_error_enum_invalid() {
        parse_err("enum A { , }");
    }

    // 呼び出し, アクセス

    #[test]
    fn test_error_call_missing_comma() {
        parse_err("foo(1 2);");
    }

    #[test]
    fn test_error_call_unclosed() {
        parse_err("foo(1, 2;");
    }

    #[test]
    fn test_error_field_access() {
        parse_err("a.;");
    }

    #[test]
    fn test_error_index_missing() {
        parse_err("a[];");
    }

    // 制御構文
    #[test]
    fn test_error_return_invalid() {
        parse_err("return return;");
    }

    #[test]
    fn test_error_break_invalid() {
        parse_err("break 1 2;");
    }

    #[test]
    fn test_error_continue_invalid() {
        parse_err("continue 1;");
    }

    // 複合エラー

    #[test]
    fn test_error_complex_1() {
        parse_fn_err("let a = if { 1; };");
    }

    #[test]
    fn test_error_complex_2() {
        parse_fn_err("let a = (1 + ); ");
    }

    #[test]
    fn test_error_complex_3() {
        parse_fn_err("while a { if b { } else }");
    }

    #[test]
    fn test_error_complex_4() {
        parse_err("fn main( { let a = 10; }");
    }
}
